import { StyleSheet, Dimensions } from "react-native";
import { COLORS } from "../../constants";
const { width, height } = Dimensions.get('window')

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.white,
    },
    brandContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: height * .03,
        marginBottom: height * .01,
        marginLeft: width * .03,
    },
    backArrow: {
        width: width * .03,
        height: height * .02,
    },
    brand: {
        width: width * .32,
        height: height * .039,
        marginLeft: width * .03,
    },

    blogs: {
        width: width * .46,
        height: height * .25,
        alignItems: 'center',
        padding: width * .03,
        margin: width * .02,
        marginTop: height * .01,
        borderRadius: width * .5,
        borderColor: '#EDEDED',
        borderWidth: 1,
        // shadowColor: "transparent",
        // shadowOpacity: 1,
        // elevation: 20, 
    },
    blogImage: {
        width: width * .2,
        height: height * .1,
        borderRadius: 50,
    },
    title: {
        fontFamily: 'Poppins SemiBold 600',
        fontSize: 10,
        lineHeight: 15,
        color: COLORS.black2,
        marginTop: height * .01,
    },
    btnTxt: {
        fontFamily: 'Poppins Regular 400',
        fontSize: 10,
        lineHeight: 15,
        color: COLORS.red,
        marginTop: height * .01,
    },
    blogDate: {
        width: width * .2,
        textAlign: 'center',
        fontFamily: 'Poppins Regular 400',
        fontSize: 8,
        lineHeight: 12,
        color: 'rgba(35, 35, 35, 0.7)',
        marginTop: height * .01,
    },
    headTxt: {
        fontFamily: 'Poppins Regular 400',
        fontSize: 15,
        lineHeight: 20,
        color: '#919191',
    },

    image: {
        width: width * .7,
        height: height * .5,
        marginTop: height * .02,
        marginBottom: height * .02,
        borderRadius: 7,
    },
    imageContainer: {
        alignItems: 'center',
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        marginTop: height * .02,
        marginBottom: height * .02,
    },
    aboutTxt: {
        color: COLORS.black,
        fontFamily: 'Poppins Regular 400',
        fontSize: 16,
        marginBottom: -5,
        textAlign: 'center',
    },
    aboutImgTxt: {
        position: 'absolute',
        color: '#9FA1AB',
        fontFamily: 'Poppins Bold 700',
        fontSize: 10,
        width: width * .2,
        top: height * .13,
        left: width * .03,
        right: width * .03,
        textAlign: 'center',
    },
    aboutBox: {
        width: width * .2,
        height: height * .02,
        backgroundColor: COLORS.yellow,
    },
    aboutImg: {
        width: width * .28,
        height: height * .2,
    },
    aboutImgBox: {
        width: width * .28,
        height: height * .2,
    },
    ratingContainer: {
        width: width * .35,
        height: height * .2,
        backgroundColor: COLORS.black,
        borderBottomRightRadius: width * .3,
        borderTopRightRadius: width * .3,
        justifyContent: 'center',
        paddingLeft: width * .03,
    },
    ratingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: height * .02,
        marginBottom: height * .02,
    },
    ratingTxt: {
        fontFamily: 'Poppins Regular 400',
        color: COLORS.white,
        fontSize: 11,
        lineHeight: 35,
    },
    starRow: {
        width: width * .2,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    star: {
        width: width * .03,
        height: height * .015,
    },
    heart1: {
        width: width * .06,
        height: height * .03,
    },
    productTitileRow:{
        flexDirection:'row',
        justifyContent:'space-between',
        
    },
    productTitile:{
        fontFamily: 'Poppins SemiBold 600',
        color: COLORS.black,
        fontSize: 16,
        lineHeight: 24,
    },
    productTxtBox:{
        marginLeft: width * .03,
        marginRight: width * .03,
        marginTop: height * .018,
    },
    productBrandName:{
        fontFamily: 'Poppins Regular 400',
        color: COLORS.black,
        fontSize: 14,
        lineHeight: 21,
        marginTop:height * .01,
    },
    priceRow:{
        flexDirection:'row',
        marginTop:height * .01,
    },
    productPrice:{
        fontFamily: 'Poppins SemiBold 600',
        color: '#FF931E',
        fontSize: 16,
        lineHeight: 24,
        marginRight: width * .03,
    },
    material:{
        fontFamily: 'Poppins SemiBold 600',
        color: COLORS.black,
        fontSize: 12,
        lineHeight: 18,
    },
    materialName:{
        fontFamily: 'Poppins Regular 400',
        color: COLORS.black,
        fontSize: 12,
        lineHeight: 18,
    },
    colorRow:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        marginTop: height * .01,
        padding: width * .03,
        borderRadius:5,
        backgroundColor: COLORS.white,
        elevation:10,
        // shadowColor:'rgba(0, 0, 0, 0.1)'
    },
    colorBox:{
        width: width * .04,
        height: height * .021,
        borderRadius: 20,
    },
    colorName:{
        fontFamily: 'Poppins Regular 400',
        color: COLORS.black,
        fontSize: 11,
        lineHeight: 12,
        marginTop:4,
    },
    colorContainer:{
        width: width * .1,
        marginLeft: width * .03,
        alignItems:'center',
    },
    rightTxt:{
        fontFamily: 'Poppins SemiBold 600',
        color: COLORS.orange1,
        fontSize: 10,
        lineHeight: 12,
        textAlign:'right',
        marginTop:height * .01,
    },
    productBtn:{
        height: height * .07,
        borderColor:COLORS.orange1,
        borderWidth:2,
        borderRadius:5,
        marginTop: height * .03,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor: COLORS.white,
    },
    productBtnText:{
        fontFamily: 'Poppins SemiBold 600',
        color: COLORS.black,
        fontSize: 16,
        lineHeight: 21,
    },
    truck:{
        width: width * .08,
        height: height * .04,
        marginRight: width * .02,
    },
    deliveryRow:{
        flexDirection:'row',
        marginTop: height * .02,
        alignItems:'center',
    },
    checkBtn:{
       width: width * .15,
        height: height * .07,
        alignItems:'center',
        justifyContent:'center',
    },
    checkBtnTxt:{
        fontFamily: 'Poppins SemiBold 600',
        color: COLORS.orange1,
        fontSize: 12,
        lineHeight: 15,
    },
    pinCodeRow:{
        width: width * .5,
        height: height * .07,
        flexDirection:'row',
        alignItems:'center',
        borderWidth:2,
        borderColor:COLORS.orange1,
        borderRadius:5,
        marginTop: height * .01,
    },
    deliveryContainer:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        marginTop: height * .02,
    },
    input:{
        width: width * .34,
        paddingLeft: width * .03,
    },
    text:{
        fontFamily: 'Poppins Regular 400',
        color: '#656565',
        fontSize: 10,
        lineHeight: 14,
        marginTop: height * .02,
        borderBottomColor: '#D8D8D8',
        borderBottomWidth:2,
        paddingBottom:height * .02,
    },
    tabTitle:{
        fontFamily: 'Poppins SemiBold 600',
        fontSize: 14,
        lineHeight: 18,
        color: COLORS.orange1,
        marginTop: height * .02,
        textAlign:'center',
    },
    tabTxt:{
        fontFamily: 'Poppins Regular 400',
        color: COLORS.black2,
        fontSize: 12,
        lineHeight: 15,
    }
})